"""Pydantic models for skill manifest parsing and validation."""

import re

from pydantic import BaseModel, Field, field_validator
from typing import Literal, Optional


_BASH_PATTERN_RE = re.compile(r"^Bash\(([^)]+):\*\)$")


def _validate_bash_entries(entries: list[str]) -> list[str]:
    """Reject bare 'Bash' and malformed Bash() patterns.

    Allowed forms:
        - Non-Bash tool names (passed through unchanged)
        - 'Bash(*)' — explicit wildcard
        - 'Bash(<prefix>:*)' — prefix-restricted

    Raises:
        ValueError if a bare 'Bash' or malformed 'Bash(...)' entry is found.
    """
    for entry in entries:
        if entry == "Bash":
            raise ValueError(
                "bare 'Bash' is not allowed; use 'Bash(*)' for wildcard "
                "or 'Bash(<prefix>:*)' to restrict commands"
            )
        if entry.startswith("Bash(") and entry != "Bash(*)":
            if not _BASH_PATTERN_RE.match(entry):
                raise ValueError(
                    f"invalid Bash pattern {entry!r}; expected 'Bash(<prefix>:*)' "
                    "or 'Bash(*)'"
                )
    return entries


class SkillMetadata(BaseModel):
    """Skill metadata section."""

    name: str
    version: str
    author: Optional[str] = None
    description: Optional[str] = None
    tags: list[str] = Field(default_factory=list)


class VolumeMount(BaseModel):
    """Volume mount configuration for containers."""

    host: str  # Host path (e.g., ~/.claude/projects)
    mode: Literal["ro", "rw"] = "ro"  # Mount mode
    # Container path is auto-generated by executor as /home/agent/workspace/<server-name>


class SkillMount(BaseModel):
    """Generic bind mount declared at spec.mounts level (independent of MCP).

    Unlike VolumeMount (which is scoped to an MCP server and has its container
    path auto-generated), SkillMount has an explicit container path so the
    skill can decide where in the container the host data appears.
    """

    host: str
    container: str
    mode: Literal["ro", "rw"] = "ro"

    @field_validator("container")
    @classmethod
    def _container_must_be_absolute(cls, v: str) -> str:
        if not v.startswith("/"):
            raise ValueError(
                f"container path must be absolute (starts with '/'), got {v!r}"
            )
        return v


class MCPServerStdio(BaseModel):
    """Stdio MCP server configuration."""

    name: str
    type: Literal["stdio"]
    command: str  # Command to run (npx, uvx, python, etc.)
    args: list[str]  # Command arguments
    mount: Optional[VolumeMount] = None
    env: list[str] = Field(default_factory=list)  # Required environment variables
    allowed_tools: list[str] = Field(default_factory=list)  # Tool whitelist (empty = all)


class MCPServerAuth(BaseModel):
    """OAuth authentication configuration for HTTP MCP servers."""

    type: Literal["oauth2", "none"]


class MCPServerHTTP(BaseModel):
    """HTTP MCP server configuration."""

    name: str
    type: Literal["http"]
    url: str  # HTTP endpoint URL
    connection: Optional[str] = None  # Connection name
    headersHelper: Optional[str] = None  # Shell command to generate headers
    env: list[str] = Field(default_factory=list)  # Required environment variables
    allowed_tools: list[str] = Field(default_factory=list)  # Tool whitelist (empty = all)
    auth: Optional[MCPServerAuth] = None  # Authentication configuration


# Union type for MCP servers
MCPServer = MCPServerStdio | MCPServerHTTP


class SkillTools(BaseModel):
    """Tool whitelist configuration."""

    builtin: list[str] = Field(default_factory=list)  # Built-in Claude Code tools

    @field_validator("builtin")
    @classmethod
    def _check_bash_pattern(cls, v: list[str]) -> list[str]:
        return _validate_bash_entries(v)


class SkillLimits(BaseModel):
    """Resource limits for skill execution."""

    max_turns: Optional[int] = None
    max_cost_usd: Optional[float] = None
    timeout_seconds: Optional[int] = None


class PhaseSpec(BaseModel):
    """Single phase declaration within a multi-phase skill."""

    id: str
    goal: str
    allowed_tools: list[str] = Field(default_factory=list)
    limits: Optional[SkillLimits] = None

    @field_validator("allowed_tools")
    @classmethod
    def _check_bash_pattern(cls, v: list[str]) -> list[str]:
        return _validate_bash_entries(v)


class SkillSpec(BaseModel):
    """Skill specification."""

    purpose: str  # Skill purpose description
    instructions: str  # Path to SKILL.md
    model: Optional[dict] = None  # Model configuration
    tools: SkillTools = Field(default_factory=SkillTools)
    mcp: list[MCPServer] = Field(default_factory=list)
    mounts: list[SkillMount] = Field(default_factory=list)  # Generic bind mounts
    limits: Optional[SkillLimits] = None
    config: dict = Field(default_factory=dict)  # Skill-specific config
    network: Optional[dict] = None  # Network allow list
    default_query: Optional[str] = None  # Default query for skill (when user runs with no args)
    children: list[str] = Field(default_factory=list)  # Child skills this skill may invoke
    # Multi-phase support (v1: documentation only, v2: strict validation)
    phases: list[PhaseSpec] = Field(default_factory=list)
    state_schema: dict = Field(default_factory=dict)  # v1: docs only

    @field_validator("children")
    @classmethod
    def _reject_path_traversal(cls, v: list[str]) -> list[str]:
        """Reject children entries that contain path traversal characters.

        Child names must be simple skill identifiers (e.g. 'daily-progress').
        Entries containing '/', '\\', or '..' are path traversal vectors and
        are rejected at validation time even though execution is sandboxed.
        """
        for entry in v:
            if "/" in entry or "\\" in entry or ".." in entry:
                raise ValueError(
                    f"children entry {entry!r} contains a path traversal sequence "
                    "('/', '\\\\', or '..'); use plain skill names only"
                )
        return v


class SkillManifest(BaseModel):
    """Complete skill manifest."""

    apiVersion: str
    kind: Literal["Skill"]
    metadata: SkillMetadata
    spec: SkillSpec
