"""Tests for Pydantic manifest models."""

import pytest
from pydantic import ValidationError
from zipsa.core.models import (
    SkillManifest,
    SkillMetadata,
    MCPServerStdio,
    MCPServerHTTP,
    MCPServerAuth,
    PhaseSpec,
    SkillMount,
    SkillTools,
    VolumeMount,
)


class TestSkillMetadata:
    """Test SkillMetadata model."""

    def test_minimal_metadata(self):
        """Minimal metadata with only required fields."""
        data = {
            "name": "test-skill",
            "version": "1.0.0",
        }
        metadata = SkillMetadata(**data)
        assert metadata.name == "test-skill"
        assert metadata.version == "1.0.0"
        assert metadata.author is None
        assert metadata.description is None
        assert metadata.tags == []

    def test_full_metadata(self):
        """Metadata with all fields."""
        data = {
            "name": "weather",
            "version": "0.1.0",
            "author": "westbrookai",
            "description": "Weather skill",
            "tags": ["weather", "utility"],
        }
        metadata = SkillMetadata(**data)
        assert metadata.name == "weather"
        assert metadata.tags == ["weather", "utility"]


class TestMCPServers:
    """Test MCP server models."""

    def test_stdio_server_minimal(self):
        """Stdio server with minimal fields."""
        data = {
            "name": "filesystem",
            "type": "stdio",
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-filesystem"],
        }
        server = MCPServerStdio(**data)
        assert server.name == "filesystem"
        assert server.type == "stdio"
        assert server.command == "npx"
        assert server.mount is None

    def test_stdio_server_with_mount(self):
        """Stdio server with mount configuration (no container path — auto-generated by executor)."""
        data = {
            "name": "sessions",
            "type": "stdio",
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-filesystem@2025.11.25"],
            "mount": {
                "host": "~/.claude/projects",
                "mode": "ro",
            },
        }
        server = MCPServerStdio(**data)
        assert server.mount is not None
        assert server.mount.host == "~/.claude/projects"
        assert server.mount.mode == "ro"
        assert not hasattr(server.mount, "container")

    def test_http_server(self):
        """HTTP MCP server."""
        data = {
            "name": "notion",
            "type": "http",
            "url": "https://mcp.notion.com/mcp",
            "connection": "notion",
        }
        server = MCPServerHTTP(**data)
        assert server.type == "http"
        assert server.url == "https://mcp.notion.com/mcp"

    def test_http_server_with_oauth2_auth(self):
        """HTTP server accepts auth.type: oauth2."""
        data = {
            "name": "notion",
            "type": "http",
            "url": "https://mcp.notion.com/mcp",
            "auth": {"type": "oauth2"},
        }
        server = MCPServerHTTP(**data)
        assert server.auth is not None
        assert server.auth.type == "oauth2"

    def test_http_server_auth_defaults_none(self):
        """HTTP server auth defaults to None."""
        data = {
            "name": "notion",
            "type": "http",
            "url": "https://mcp.notion.com/mcp",
        }
        server = MCPServerHTTP(**data)
        assert server.auth is None

    def test_http_server_auth_type_none(self):
        """HTTP server auth.type: none is valid."""
        data = {
            "name": "notion",
            "type": "http",
            "url": "https://mcp.notion.com/mcp",
            "auth": {"type": "none"},
        }
        server = MCPServerHTTP(**data)
        assert server.auth.type == "none"

    def test_manifest_with_oauth2_server(self, tmp_path):
        """Full manifest parsing with oauth2 auth."""
        import yaml
        manifest_yaml = tmp_path / "manifest.yaml"
        manifest_yaml.write_text("""
apiVersion: zipsa.dev/v1alpha1
kind: Skill
metadata:
  name: test-oauth
  version: 1.0.0
spec:
  purpose: Test
  instructions: ./SKILL.md
  mcp:
    - name: notion
      type: http
      url: https://mcp.notion.com/mcp
      auth:
        type: oauth2
  tools:
    builtin: []
""")
        data = yaml.safe_load(manifest_yaml.read_text())
        manifest = SkillManifest.model_validate(data)
        assert manifest.spec.mcp[0].auth.type == "oauth2"


class TestSkillManifest:
    """Test full SkillManifest model."""

    def test_minimal_manifest(self):
        """Minimal valid manifest."""
        data = {
            "apiVersion": "zipsa.dev/v1alpha1",
            "kind": "Skill",
            "metadata": {
                "name": "test",
                "version": "1.0.0",
            },
            "spec": {
                "purpose": "Test skill",
                "instructions": "./SKILL.md",
            },
        }
        manifest = SkillManifest.model_validate(data)
        assert manifest.kind == "Skill"
        assert manifest.metadata.name == "test"
        assert manifest.spec.purpose == "Test skill"

    def test_manifest_with_mcp_stdio(self):
        """Manifest with MCP stdio server."""
        data = {
            "apiVersion": "zipsa.dev/v1alpha1",
            "kind": "Skill",
            "metadata": {"name": "test", "version": "1.0.0"},
            "spec": {
                "purpose": "Test",
                "instructions": "./SKILL.md",
                "mcp": [
                    {
                        "name": "filesystem",
                        "type": "stdio",
                        "command": "npx",
                        "args": ["-y", "@modelcontextprotocol/server-filesystem"],
                    }
                ],
            },
        }
        manifest = SkillManifest.model_validate(data)
        assert len(manifest.spec.mcp) == 1
        assert manifest.spec.mcp[0].name == "filesystem"

    def test_manifest_with_builtin_tools(self):
        """Manifest with builtin tool whitelist."""
        data = {
            "apiVersion": "zipsa.dev/v1alpha1",
            "kind": "Skill",
            "metadata": {"name": "test", "version": "1.0.0"},
            "spec": {
                "purpose": "Test",
                "instructions": "./SKILL.md",
                "tools": {"builtin": ["WebFetch", "Bash(*)"]},
            },
        }
        manifest = SkillManifest.model_validate(data)
        assert "WebFetch" in manifest.spec.tools.builtin
        assert "Bash(*)" in manifest.spec.tools.builtin

    def test_mcp_server_allowed_tools(self):
        """MCP server allowed_tools lives on the server definition."""
        data = {
            "apiVersion": "zipsa.dev/v1alpha1",
            "kind": "Skill",
            "metadata": {"name": "test", "version": "1.0.0"},
            "spec": {
                "purpose": "Test",
                "instructions": "./SKILL.md",
                "mcp": [
                    {
                        "name": "sessions",
                        "type": "stdio",
                        "command": "npx",
                        "args": ["@modelcontextprotocol/server-filesystem@2025.11.25"],
                        "allowed_tools": ["read_file", "list_directory"],
                    },
                    {
                        "name": "notion",
                        "type": "http",
                        "url": "https://mcp.notion.com/mcp",
                        "allowed_tools": ["notion-search", "notion-create-pages"],
                    },
                ],
            },
        }
        manifest = SkillManifest.model_validate(data)
        sessions = manifest.spec.mcp[0]
        assert sessions.allowed_tools == ["read_file", "list_directory"]
        notion = manifest.spec.mcp[1]
        assert notion.allowed_tools == ["notion-search", "notion-create-pages"]

    def test_mcp_server_allowed_tools_defaults_empty(self):
        """allowed_tools defaults to empty list (allow all tools from server)."""
        data = {
            "name": "filesystem",
            "type": "stdio",
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-filesystem"],
        }
        server = MCPServerStdio(**data)
        assert server.allowed_tools == []

    def test_invalid_kind(self):
        """Invalid kind should fail validation."""
        data = {
            "apiVersion": "zipsa.dev/v1alpha1",
            "kind": "Invalid",
            "metadata": {"name": "test", "version": "1.0.0"},
            "spec": {"purpose": "Test", "instructions": "./SKILL.md"},
        }
        with pytest.raises(ValidationError):
            SkillManifest.model_validate(data)

    def test_missing_required_field(self):
        """Missing required field should fail validation."""
        data = {
            "apiVersion": "zipsa.dev/v1alpha1",
            "kind": "Skill",
            # Missing metadata
            "spec": {"purpose": "Test", "instructions": "./SKILL.md"},
        }
        with pytest.raises(ValidationError):
            SkillManifest.model_validate(data)


class TestBashToolPatternValidation:
    """Bash tool entries must use Bash(*) or Bash(prefix:*); bare 'Bash' is rejected."""

    def test_phase_bare_bash_rejected(self):
        with pytest.raises(ValidationError, match="Bash"):
            PhaseSpec(id="x", goal="g", allowed_tools=["Bash"])

    def test_phase_bash_wildcard_ok(self):
        phase = PhaseSpec(id="x", goal="g", allowed_tools=["Bash(*)"])
        assert "Bash(*)" in phase.allowed_tools

    def test_phase_bash_prefix_ok(self):
        phase = PhaseSpec(
            id="x", goal="g", allowed_tools=["Bash(git:*)", "Bash(find:*)"]
        )
        assert len(phase.allowed_tools) == 2

    def test_phase_invalid_bash_syntax_rejected(self):
        with pytest.raises(ValidationError, match="Bash"):
            PhaseSpec(id="x", goal="g", allowed_tools=["Bash(git)"])

    def test_phase_other_tools_pass_through(self):
        phase = PhaseSpec(
            id="x",
            goal="g",
            allowed_tools=["Read", "Edit", "mcp__notion__notion-search"],
        )
        assert len(phase.allowed_tools) == 3

    def test_skilltools_bare_bash_rejected(self):
        with pytest.raises(ValidationError, match="Bash"):
            SkillTools(builtin=["Bash"])

    def test_skilltools_bash_wildcard_ok(self):
        tools = SkillTools(builtin=["Bash(*)"])
        assert tools.builtin == ["Bash(*)"]

    def test_skilltools_other_tools_ok(self):
        tools = SkillTools(builtin=["Read", "Edit"])
        assert tools.builtin == ["Read", "Edit"]


class TestSkillMount:
    """spec.mounts entry — generic host:container bind mount, independent of MCP servers."""

    def test_minimal_mount(self):
        m = SkillMount(host="~/data", container="/data")
        assert m.host == "~/data"
        assert m.container == "/data"
        assert m.mode == "ro"   # safe default

    def test_explicit_rw(self):
        m = SkillMount(host="~/data", container="/data", mode="rw")
        assert m.mode == "rw"

    def test_missing_host_rejected(self):
        with pytest.raises(ValidationError):
            SkillMount(container="/data")

    def test_missing_container_rejected(self):
        with pytest.raises(ValidationError):
            SkillMount(host="~/data")

    def test_invalid_mode_rejected(self):
        with pytest.raises(ValidationError):
            SkillMount(host="~/data", container="/data", mode="bogus")

    def test_container_must_be_absolute(self):
        with pytest.raises(ValidationError, match="absolute"):
            SkillMount(host="~/data", container="relative/path")


class TestSpecMounts:
    """spec.mounts is an optional list of SkillMount entries."""

    def test_defaults_empty(self):
        data = {
            "apiVersion": "zipsa.dev/v1alpha1",
            "kind": "Skill",
            "metadata": {"name": "test", "version": "1.0.0"},
            "spec": {"purpose": "T", "instructions": "./SKILL.md"},
        }
        manifest = SkillManifest.model_validate(data)
        assert manifest.spec.mounts == []

    def test_multiple_mounts_parsed(self):
        data = {
            "apiVersion": "zipsa.dev/v1alpha1",
            "kind": "Skill",
            "metadata": {"name": "test", "version": "1.0.0"},
            "spec": {
                "purpose": "T",
                "instructions": "./SKILL.md",
                "mounts": [
                    {"host": "~/.claude/projects", "container": "/home/agent/claude-projects", "mode": "ro"},
                    {"host": "~/data", "container": "/data", "mode": "rw"},
                ],
            },
        }
        manifest = SkillManifest.model_validate(data)
        assert len(manifest.spec.mounts) == 2
        assert manifest.spec.mounts[0].container == "/home/agent/claude-projects"
        assert manifest.spec.mounts[1].mode == "rw"


class TestDefaultQuery:
    """SkillSpec.default_query is an optional string used by the launcher
    when the user invokes the skill with no query argument."""

    def _spec(self, **overrides):
        from zipsa.core.models import SkillSpec
        data = {
            "purpose": "test",
            "instructions": "./SKILL.md",
        }
        data.update(overrides)
        return SkillSpec.model_validate(data)

    def test_default_query_absent_is_none(self):
        spec = self._spec()
        assert spec.default_query is None

    def test_default_query_accepts_string(self):
        spec = self._spec(default_query="Say hello.")
        assert spec.default_query == "Say hello."

    def test_default_query_empty_string_treated_as_empty(self):
        """Empty string is a valid (but odd) value — it explicitly
        opts INTO the empty-input → agent-intro path. Not None."""
        spec = self._spec(default_query="")
        assert spec.default_query == ""


class TestChildren:
    """SkillSpec.children declares which other skills this skill may invoke
    via Bash(zipsa:*). Optional list[str]; defaults to []."""

    def _spec(self, **overrides):
        from zipsa.core.models import SkillSpec
        data = {
            "purpose": "test",
            "instructions": "./SKILL.md",
        }
        data.update(overrides)
        return SkillSpec.model_validate(data)

    def test_children_absent_defaults_to_empty_list(self):
        spec = self._spec()
        assert spec.children == []

    def test_children_accepts_list_of_strings(self):
        spec = self._spec(children=["daily-progress", "bip-daily-x"])
        assert spec.children == ["daily-progress", "bip-daily-x"]

    def test_children_rejects_non_string_entries(self):
        with pytest.raises(ValidationError):
            self._spec(children=["valid-name", 42, None])

    def test_children_rejects_path_traversal(self):
        """Children entries with '/', '\\', or '..' must be rejected."""
        from pydantic import ValidationError
        for bad in ["../escape", "skill/with-slash", "..", "skill\\..\\other"]:
            with pytest.raises(ValidationError):
                self._spec(children=[bad])


class TestRequiresEntry:
    def test_directory_type_loads(self):
        from zipsa.core.models import RequiresEntry
        e = RequiresEntry(type="directory", prompt="Where?")
        assert e.type == "directory"
        assert e.prompt == "Where?"

    def test_list_directory_type_loads(self):
        from zipsa.core.models import RequiresEntry
        e = RequiresEntry(type="list[directory]", prompt="List them")
        assert e.type == "list[directory]"

    def test_string_type_loads(self):
        from zipsa.core.models import RequiresEntry
        e = RequiresEntry(type="string", prompt="Tell me")
        assert e.type == "string"

    def test_unsupported_type_rejected(self):
        from pydantic import ValidationError
        from zipsa.core.models import RequiresEntry
        with pytest.raises(ValidationError):
            RequiresEntry(type="int", prompt="How many?")

    def test_empty_prompt_rejected(self):
        from pydantic import ValidationError
        from zipsa.core.models import RequiresEntry
        with pytest.raises(ValidationError):
            RequiresEntry(type="directory", prompt="")

    def test_requires_block_in_spec_loads(self):
        from zipsa.core.models import SkillSpec
        spec = SkillSpec(
            purpose="test",
            instructions="./SKILL.md",
            requires={
                "project_roots": {"type": "list[directory]", "prompt": "Where?"},
            },
        )
        assert "project_roots" in spec.requires
        assert spec.requires["project_roots"].type == "list[directory]"

    def test_requires_key_must_be_lowercase_underscore(self):
        from pydantic import ValidationError
        from zipsa.core.models import SkillSpec
        with pytest.raises(ValidationError, match="lowercase"):
            SkillSpec(
                purpose="test",
                instructions="./SKILL.md",
                requires={"BadKey": {"type": "string", "prompt": "?"}},
            )

    def test_requires_key_must_not_have_dot(self):
        from pydantic import ValidationError
        from zipsa.core.models import SkillSpec
        with pytest.raises(ValidationError):
            SkillSpec(
                purpose="test",
                instructions="./SKILL.md",
                requires={"a.b": {"type": "string", "prompt": "?"}},
            )

    def test_requires_empty_dict_is_default(self):
        from zipsa.core.models import SkillSpec
        spec = SkillSpec(purpose="test", instructions="./SKILL.md")
        assert spec.requires == {}


class TestDynamicMount:
    def test_static_mount_still_works(self):
        from zipsa.core.models import SkillMount
        m = SkillMount(host="~/x", container="/y", mode="ro")
        assert m.host == "~/x"
        assert m.source is None
        assert m.container_prefix is None

    def test_source_with_container_loads(self):
        from zipsa.core.models import SkillMount
        m = SkillMount(source="requires.obsidian_vault", container="/vault", mode="ro")
        assert m.source == "requires.obsidian_vault"
        assert m.container == "/vault"
        assert m.host is None

    def test_source_with_container_prefix_loads(self):
        from zipsa.core.models import SkillMount
        m = SkillMount(source="requires.project_roots", container_prefix="/projects/", mode="ro")
        assert m.source == "requires.project_roots"
        assert m.container_prefix == "/projects/"

    def test_host_and_source_together_rejected(self):
        from pydantic import ValidationError
        from zipsa.core.models import SkillMount
        with pytest.raises(ValidationError, match="mutually exclusive"):
            SkillMount(host="~/x", source="requires.y", container="/z")

    def test_container_and_container_prefix_together_rejected(self):
        from pydantic import ValidationError
        from zipsa.core.models import SkillMount
        with pytest.raises(ValidationError, match="container and container_prefix"):
            SkillMount(source="requires.y", container="/z", container_prefix="/zz/")

    def test_container_prefix_must_end_with_slash(self):
        from pydantic import ValidationError
        from zipsa.core.models import SkillMount
        with pytest.raises(ValidationError, match="end with '/'"):
            SkillMount(source="requires.y", container_prefix="/projects")

    def test_source_without_container_or_prefix_rejected(self):
        from pydantic import ValidationError
        from zipsa.core.models import SkillMount
        with pytest.raises(ValidationError, match="must set"):
            SkillMount(source="requires.y")

    def test_neither_host_nor_source_rejected(self):
        from pydantic import ValidationError
        from zipsa.core.models import SkillMount
        with pytest.raises(ValidationError, match="must set"):
            SkillMount(container="/y")

    def test_source_must_start_with_requires_dot(self):
        from pydantic import ValidationError
        from zipsa.core.models import SkillMount
        with pytest.raises(ValidationError, match="requires\\."):
            SkillMount(source="config.x", container="/y")

    def test_host_with_container_prefix_rejected(self):
        from pydantic import ValidationError
        from zipsa.core.models import SkillMount
        with pytest.raises(ValidationError, match="static mounts.*cannot use container_prefix"):
            SkillMount(host="~/x", container_prefix="/y/")


class TestRequiresMountIntegration:
    def test_source_referencing_existing_key_passes(self):
        from zipsa.core.models import SkillSpec
        spec = SkillSpec(
            purpose="t", instructions="./SKILL.md",
            requires={"project_roots": {"type": "list[directory]", "prompt": "?"}},
            mounts=[{"source": "requires.project_roots", "container_prefix": "/projects/"}],
        )
        assert spec.mounts[0].source == "requires.project_roots"

    def test_source_referencing_unknown_key_rejected(self):
        from pydantic import ValidationError
        from zipsa.core.models import SkillSpec
        with pytest.raises(ValidationError, match="unknown requires key"):
            SkillSpec(
                purpose="t", instructions="./SKILL.md",
                requires={"project_roots": {"type": "list[directory]", "prompt": "?"}},
                mounts=[{"source": "requires.nonexistent", "container": "/x"}],
            )

    def test_directory_type_must_use_container(self):
        from pydantic import ValidationError
        from zipsa.core.models import SkillSpec
        with pytest.raises(ValidationError, match="container.*for single directory"):
            SkillSpec(
                purpose="t", instructions="./SKILL.md",
                requires={"obsidian_vault": {"type": "directory", "prompt": "?"}},
                mounts=[{"source": "requires.obsidian_vault", "container_prefix": "/v/"}],
            )

    def test_list_directory_type_must_use_container_prefix(self):
        from pydantic import ValidationError
        from zipsa.core.models import SkillSpec
        with pytest.raises(ValidationError, match="container_prefix.*for list"):
            SkillSpec(
                purpose="t", instructions="./SKILL.md",
                requires={"project_roots": {"type": "list[directory]", "prompt": "?"}},
                mounts=[{"source": "requires.project_roots", "container": "/x"}],
            )

    def test_string_type_cannot_be_mount_source(self):
        from pydantic import ValidationError
        from zipsa.core.models import SkillSpec
        with pytest.raises(ValidationError, match="cannot be used as a mount source"):
            SkillSpec(
                purpose="t", instructions="./SKILL.md",
                requires={"voice": {"type": "string", "prompt": "?"}},
                mounts=[{"source": "requires.voice", "container": "/x"}],
            )
